<div class="contact-unit full-height unit-padding">
    <div class="page-unit">
        <h1>Contact</h1>
        <br>
        <section class="row">
            <article class="col-md-8">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2911.9863105878408!2d-77.58771554899057!3d43.125813779040556!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89d6b5387cd9b7bb%3A0x9b8b6d3c5fb8e153!2sBrighton%2C+NY+14620!5e0!3m2!1sen!2sus!4v1450438634673" allowfullscreen class="img-responsive"></iframe>
            </article>
            <aside class="col-md-4">
                <p>2232 South Elmwood Street<br>Rochester, NY 14627<br>
                    <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> 585-783-7776
                    <br>
                </p>
            </aside>
            <aside class="col-md-4">
                <br><br>
                <p><span class="bold">For General Feedback:</span><br>

                    Contact the owner Ms. Banda at<br> <span class="bold"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> 609-890-6904.</span></p>

                    <blockquote>"We are always trying to push ourselves to do more for our customers. I would love to hear your Feedback!"</blockquote>
                
            </aside>
        </section>
                

        <section class="row">
            <br>
            <h3><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Job Postings</h3>
            <p class="center"><span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span> None Available<br>
                Currently there are no open positions. When a position opens up, it will be posted here. <br><br></p>
        </section>
                



    </div>
</div>
