<div class="credits l-wrap">
	<p class="row"><a href="http://memeheroes.com/wp-content/uploads/2015/02/Joben-Bistro.jpg">Landing page background </a>|
	<a href="http://oldhousenorthampton.com/wp-content/uploads/2013/06/1500x1000_food4.jpg">Menu page background </a>|
	<a href="http://cdn.pastemagazine.com/www/articles/image3.JPG">Play page background </a>|
	<a href="https://scripted.com/wp-content/uploads/2014/02/Contact_Background.png">Contact page background </a>|
	<a href="http://www.i-learn.be/wp-content/uploads/2015/10/Mans-Hands-Typing-On-Laptop-With-Smartphone-Book-And-Coffee.jpg">Colophon page background </a>|
	<a href="http://www.freepik.com/">Vectors</a>

	</p>
</div>