<div class="l-hours l-wrap white_center">
	<div class="bad-script table_display">Sun<br>10am-1am</div>
	<div class="bad-script table_display">Mon<br>12pm-1am</div>
	<div class="bad-script table_display">Tues<br>12pm-3am</div>
	<div class="bad-script table_display">Wed<br>12pm-3am</div>
	<div class="bad-script table_display">Thurs<br>12pm-3am</div>
	<div class="bad-script table_display">Fri<br>12pm-3am</div>
	<div class="bad-script table_display">Sat<br>10am-3am</div>
</div>