<div class="menu-unit full-height unit-padding">
            <div class="page-unit">
                <h1>Menu</h1>
                <section>
                    <div class="col-md-4">
                        <h4>Appetizers</h4>
                        <p class="left-align">
                            Chicken Pita Pizza...................................$5 <br>
                            Saug and Carb*.........................................$5 <br>
                            Fried Calamari Rings..............................$6<br>
                            Bowl of Seasonal Fruit...........................$4 <br>
                            Parmesian Fries........................................$4 <br>
                            <br>
                        </p>                        
                    </div>
                    <div class="col-md-4">
                        <h4>Entrees</h4>
                        <p class="left-align">
                            Que Pub Burger........................................$10 <br>
                            Chicken and Waffles:<br>
                            Que Pub style*...........................................$9<br>
                            3 Quesadillas: <br>
                            Pork, Chicken, or Cactus.......................$7 <br>
                            Lasagna: <br>
                            Lobster, Meat, or Spinach......................$8<br>
                            Alfredo Pasta w/Lemon Shrimp..........$9<br>
                            Baja Fish Tacos...........................................$9<br>
                            Chicken Tamales: <br>
                            Green or Red...............................................$9<br>
                            <br>
                        </p>
                    </div>
                    <div class="col-md-4"><h4>Drink Specials</h4>
                        <p class="left-align">
                            Sunday:Mimosas..................................$3<br>
                            Monday:Wells.......................................$4<br>
                            Tuesday:Tequila Shots.......................$2<br>
                            Wednesday:Beers................................$3<br>
                            Thursday:Any Shot..............................$2<br>
                            Friday:Cocktails....................................$6<br>
                            Saturday:All-you-can-drink..............$20<br>
                            <br>
                        </p>                   
                    </div>
                </section>
            </div>
        </div>