<nav class="navbar navbar-inverse navbar-fixed-top back-transparent">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <a onclick="scrollpage('main-unit');"><img class="l-brand" alt="Brand" src="img/quelogo.svg" onclick="scrollpage('main-unit');"></a>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a onclick="scrollpage('menu-unit');" id="menu-nav">Menu</a></li>
        <li><a onclick="scrollpage('play-unit');" id="play-nav">Play</a></li>
        <li><a onclick="scrollpage('contact-unit');" id="contact-nav">Contact</a></li>
        <li><a onclick="scrollpage('colophon-unit');" id="colophon-nav">Colophon</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
