<div class="play-unit full-height unit-padding">
    <div class="page-unit">
        <h1>Play</h1>
        <br>
        <section class="row">
            <article class="col-md-8">
                <iframe src="https://www.youtube.com/embed/HMbVdrL1O58?rel=0&amp;showinfo=0" allowfullscreen class="img-responsive"></iframe>
                <br><br>
            </article>
            <aside class="col-md-4"> 
                <p>At Que Pub we believe that play should always be mixed with drinks and eating! We have 2 brand new pool tables, 4 dart boards, and 20+ different board games including giant jenga!
                <br><br>
                </p>
                <p id="announcement">Happy Hour!<br>
                    Everday 6-7pm, a game is chosen to play where the winner will win an appetizer or free shots!
                </p>
                <br>
            </aside>
        </section>

        <section class="row">
            <fieldset>
            <legend>Some of the Available Games</legend>
                <div class="col-xs-6 col-sm-2">Giant Jenga</div>
                <div class="col-xs-6 col-sm-2">Monopoly</div>
                <div class="col-xs-6 col-sm-2">Twister </div>
                <div class="col-xs-6 col-sm-2">Battleship</div>
                <div class="col-xs-6 col-sm-1">Quelf</div>
                <div class="col-xs-6 col-sm-3 center">Apples to Apples</div>
                <div class="col-xs-6 col-sm-2">The Game of Things</div>
                <div class="col-xs-6 col-sm-2">Operation</div>
                <div class="col-xs-6 col-sm-2">Catchphrase</div>
                <div class="col-xs-6 col-sm-2">Bananagrams</div>
                <div class="col-xs-6 col-sm-1">Clue</div>
                <div class="col-xs-6 col-sm-3 center">Cards Against Humanity</div>
            </fieldset>
        </section>

    </div>
</div>